ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS device_type TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS os_name TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS browser_name TEXT;
